output_folder: data
channel_ids:
  - UCSVnFkCHaJc7bye__yDDJIQ  #Linzy Bacbotte
  #- UCmCnw2uYIjCKXwu3ma1NABQ #Laura Beg
  #- UCP4L5WbOjXHbVi4EMSTfkoA #plokpone
  #- UCoZpT6oNLCCpZRgXwIBJWBA #Sega nou zanset
  #- UCjlLBy8WRmRg_v4W6oj5JbQ #sega tunes