output_folder: data
channel_ids:
  - UC-lHJZR3Gqxm24_Vd_AJ5Yw  # PewDiePie
  - UC295-Dw_tDNtZXFeAPAW6Aw  # 5-Minute Crafts
  - UCX6OQ3DkcsbYNE6H8uQQuVA  # MrBeast
  - UCRijo3ddMTht_IHyNSNXpNQ  # Dude Perfect
  - UC4rlAVgAK0SGk-yTfe48Qpw  # BRIGHT SIDE
  - UCp0hYYBW6IMayGgR-WeoCvQ  # TheEllenShow
  - UC7_YxT-KID8kRbqZo7MyscQ  # Markiplier
  - UC8-Th83bH_thdKZDJCrn88g  # The Tonight Show Starring Jimmy Fallon
