output_folder: data

channel_ids:

  - UCUTKfIEm5zcly_uRRWQjZAA # Ride On Records

  - UCTO5zB_nfvNsP-KUR5d6yXA # rn019

  - UCmCnw2uYIjCKXwu3ma1NABQ # Laura Beg - Topic

  - UCe98Py0NYdyp5Ekb7-C7Scg # Clarel Armelle

  - UClXb8zo_Lnsh42GgxEPCbFw # Jerry N The Resistance